### ISSUE TITLE
"yo easy-ui5 project"  ends with error

### ISSUE THREAD

**Issue by I501000** [SAP/generator-easy-ui5#101]
## Easy-Ui5 version:
4.30
> Run `yo easy-ui5 --plugins` to print all relevant version strings

## OS/version:

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎5/‎12/‎2021
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

## Steps to reproduce the problem:

1. Step 1
C:\Users\IXXXXXX>yo easy-ui5 --plugins
Error easy-ui5 --plugins

Unexpected token '.'
3. Step 2
C:\Users\I501000>yo easy-ui5 project
Error easy-ui5 project

Unexpected token '.'

## What is the expected result?

generate a ui5 project 

## What happens instead?

ends with error

## Any other information? (attach screenshot if possible)
![image](https://user-images.githubusercontent.com/74337345/159377569-2bc65541-127e-4182-90a9-ebfd0ae834bf.png)

**Comment by nicogeburek** [comment]
Hi! What node version are you running? Make sure it's 14 or higher. BR, Nico

**Comment by I501000** [comment]
Hi  Nico,

Node version is v12.21.0 on my laptop .

**Comment by nicogeburek** [comment]
Update to version 14 or higher and you should be good to go. I'm confident it's that because we had this issue before (#96).

BR, Nico
