### ISSUE TITLE
Getting error "Unexpected token '.'"

### ISSUE THREAD

**Issue by FarooqKoppal** [SAP/generator-easy-ui5#107]
On trying to generate a project using the command yo easy-ui5 it ran into an error as Unexpected token '.'
![Yo error](https://user-images.githubusercontent.com/19686714/176984676-28c0643f-4247-46bc-a325-1d8a7020fb41.png)

**Comment by vobu** [comment]
are you using a Node version >= 14?

**Comment by FarooqKoppal** [comment]
> 

The node version is v12.22.3 on my system

**Comment by FarooqKoppal** [comment]
> are you using a Node version >= 14?

Current node version is v12.22.3
