### ISSUE TITLE
Not able to install generator-easy-ui5 dependency 

### ISSUE THREAD

**Issue by shaancse08** [SAP/generator-easy-ui5#108]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @octokit/plugin-paginate-rest@2.21.2
npm WARN Found: @octokit/core@3.6.0
npm WARN node_modules/generator-easy-ui5/node_modules/@octokit/core
npm WARN   peer @octokit/core@"^3.5.0" from @octokit/plugin-throttling@3.7.0
npm WARN   node_modules/generator-easy-ui5/node_modules/@octokit/plugin-throttling
npm WARN     @octokit/plugin-throttling@"^3.5.2" from generator-easy-ui5@3.3.0
npm WARN     node_modules/generator-easy-ui5
npm WARN   3 more (@octokit/rest, @octokit/plugin-request-log, @octokit/plugin-rest-endpoint-methods)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @octokit/core@">=4" from @octokit/plugin-paginate-rest@2.21.2
npm WARN node_modules/generator-easy-ui5/node_modules/@octokit/plugin-paginate-rest
npm WARN   @octokit/plugin-paginate-rest@"^2.16.8" from @octokit/rest@18.12.0
npm WARN   node_modules/generator-easy-ui5/node_modules/@octokit/rest
npm WARN
npm WARN Conflicting peer dependency: @octokit/core@4.0.4
npm WARN node_modules/@octokit/core
npm WARN   peer @octokit/core@">=4" from @octokit/plugin-paginate-rest@2.21.2
npm WARN   node_modules/generator-easy-ui5/node_modules/@octokit/plugin-paginate-rest
npm WARN     @octokit/plugin-paginate-rest@"^2.16.8" from @octokit/rest@18.12.0
npm WARN     node_modules/generator-easy-ui5/node_modules/@octokit/rest
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
npm ERR! code 1
npm ERR! path AppData\Roaming\npm\node_modules\generator-easy-ui5
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c AppData\Local\Temp\postinstall65787389797.cmd
npm ERR! AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\@octokit\request\dist-node\index.js:108
npm ERR!     throw new requestError.RequestError(error.message, 500, {
npm ERR!           ^
npm ERR!
npm ERR! RequestError [HttpError]: request to https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main failed, reason: getaddrinfo ENOTFOUND api.github.com
npm ERR!     at AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\@octokit\request\dist-node\index.js:108:11
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async AppData\Roaming\npm\node_modules\generator-easy-ui5\generators\app\postinstall.js:44:21 {
npm ERR!   status: 500,
npm ERR!   request: {
npm ERR!     method: 'GET',
npm ERR!     url: 'https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main',
npm ERR!     headers: {
npm ERR!       accept: 'application/vnd.github.v3+json',
npm ERR!       'user-agent': 'generator-easy-ui5 octokit-rest.js/18.12.0 octokit-core.js/3.6.0 Node.js/18.6.0 (win32; x64)'
npm ERR!     },
npm ERR!     request: { hook: [Function: bound bound register] }
npm ERR!   }
npm ERR! }
npm ERR!
npm ERR! Node.js v18.6.0

npm ERR! A complete log of this run can be found in:
npm ERR!    AppData\Local\npm-cache\_logs\2022-07-15T08_28_59_594Z-debug-0.log

**Comment by petermuessig** [comment]
Are you working offline or behind a proxy? 

```
RequestError [HttpError]: request to https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main failed, reason: getaddrinfo ENOTFOUND api.github.com
```

indicates that you can't access the GitHub REST API.

**Comment by shaancse08** [comment]
Nope I am not working offline neither with VPN or proxy.

**Comment by petermuessig** [comment]
Can you maybe share the complete log? 

```
npm ERR! AppData\Local\npm-cache_logs\2022-07-15T08_28_59_594Z-debug-0.log
```

From command line, can you curl `https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main` ?

**Comment by shaancse08** [comment]
{
  "name": "main",
  "commit": {
    "sha": "fb9fbf274d24f5f18ca987fa0ae3a34fc1e676b9",
    "node_id": "C_kwDOFOad6toAKGZiOWZiZjI3NGQyNGY1ZjE4Y2E5ODdmYTBhZTNhMzRmYzFlNjc2Yjk",
    "commit": {
      "author": {
        "name": "Nico Geburek",
        "email": "nicolai.geburek@sap.com",
        "date": "2022-07-26T07:40:14Z"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "date": "2022-07-26T07:40:14Z"
      },
      "message": "Merge pull request #51 from nicogeburek/main\n\nfix: add destination content to mta.yaml #49",
      "tree": {
        "sha": "b86e4e72d175d0104a97d8255976168136d1a327",
        "url": "https://api.github.com/repos/ui5-community/generator-ui5-project/git/trees/b86e4e72d175d0104a97d8255976168136d1a327"
      },
      "url": "https://api.github.com/repos/ui5-community/generator-ui5-project/git/commits/fb9fbf274d24f5f18ca987fa0ae3a34fc1e676b9",
      "comment_count": 0,
      "verification": {
        "verified": true,
        "reason": "valid",
        "signature": "-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJi35peCRBK7hj4Ov3rIwAAP40IAAPMfH9/O/kpYb8UaYnP8QFK\n+eO1IJRCrc2ad50pfRrgEtM150T3ahYzLINjyUqQWE5ZKdHLzf37Ha8fcPrMYCJv\nFUPBCZzaW7/GK2kpiY3i8ZQGl0PHhIEQni741V4x6NHoHGPY6xTa0BiLpMsQxpKO\ndHoO1CUvjFCUWBtluhnq2nzlfSnysopd5EZ3UvUIVMi7IQRW8vt+IfPUS/urYJPb\nxZ+6+LgwWeCkbWZZyWTJRublb/jCnqDUsm4CqRfiaMI/7DKE4LguGKg7WkKY8iSn\n4KZgFVWJ4wNUjnWbr6hCoJUoX/bmaqK0+xmfTxYpRcnCr0Myx1U08skLBBHqf00=\n=9OHA\n-----END PGP SIGNATURE-----\n",
        "payload": "tree b86e4e72d175d0104a97d8255976168136d1a327\nparent 4fac1422698a9bd136f4186532825b2956316321\nparent 62c53eab2795d5f38be9a58d217998596526f372\nauthor Nico Geburek <nicolai.geburek@sap.com> 1658821214 +0200\ncommitter GitHub <noreply@github.com> 1658821214 +0200\n\nMerge pull request #51 from nicogeburek/main\n\nfix: add destination content to mta.yaml #49"
      }
    },
    "url": "https://api.github.com/repos/ui5-community/generator-ui5-project/commits/fb9fbf274d24f5f18ca987fa0ae3a34fc1e676b9",
    "html_url": "https://github.com/ui5-community/generator-ui5-project/commit/fb9fbf274d24f5f18ca987fa0ae3a34fc1e676b9",
    "comments_url": "https://api.github.com/repos/ui5-community/generator-ui5-project/commits/fb9fbf274d24f5f18ca987fa0ae3a34fc1e676b9/comments",
    "author": {
      "login": "nicogeburek",
      "id": 65965098,
      "node_id": "MDQ6VXNlcjY1OTY1MDk4",
      "avatar_url": "https://avatars.githubusercontent.com/u/65965098?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nicogeburek",
      "html_url": "https://github.com/nicogeburek",
      "followers_url": "https://api.github.com/users/nicogeburek/followers",
      "following_url": "https://api.github.com/users/nicogeburek/following{/other_user}",
      "gists_url": "https://api.github.com/users/nicogeburek/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nicogeburek/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nicogeburek/subscriptions",
      "organizations_url": "https://api.github.com/users/nicogeburek/orgs",
      "repos_url": "https://api.github.com/users/nicogeburek/repos",
      "events_url": "https://api.github.com/users/nicogeburek/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nicogeburek/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "web-flow",
      "id": 19864447,
      "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/web-flow",
      "html_url": "https://github.com/web-flow",
      "followers_url": "https://api.github.com/users/web-flow/followers",
      "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
      "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
      "organizations_url": "https://api.github.com/users/web-flow/orgs",
      "repos_url": "https://api.github.com/users/web-flow/repos",
      "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/web-flow/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "sha": "4fac1422698a9bd136f4186532825b2956316321",
        "url": "https://api.github.com/repos/ui5-community/generator-ui5-project/commits/4fac1422698a9bd136f4186532825b2956316321",
        "html_url": "https://github.com/ui5-community/generator-ui5-project/commit/4fac1422698a9bd136f4186532825b2956316321"
      },
      {
        "sha": "62c53eab2795d5f38be9a58d217998596526f372",
        "url": "https://api.github.com/repos/ui5-community/generator-ui5-project/commits/62c53eab2795d5f38be9a58d217998596526f372",
        "html_url": "https://github.com/ui5-community/generator-ui5-project/commit/62c53eab2795d5f38be9a58d217998596526f372"
      }
    ]
  },
  "_links": {
    "self": "https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main",
    "html": "https://github.com/ui5-community/generator-ui5-project/tree/main"
  },
  "protected": false,
  "protection": {
    "enabled": false,
    "required_status_checks": {
      "enforcement_level": "off",
      "contexts": [

      ],
      "checks": [

      ]
    }
  },
  "protection_url": "https://api.github.com/repos/ui5-community/generator-ui5-project/branches/main/protection"
}

**Comment by petermuessig** [comment]
@shaancse08 does the issue still exist? This is really weird. On command line it works with `curl` but the octokit client fails to connect to its own endpoint. :-/ It somehow seems that the octokit client fails to resolve api.github.com which internally uses the https.get api...

Can you run the following on your command line:
```sh
node -e "https.get(\"https://api.github.com\", (r) => { console.log(\"Works\") }).on(\"error\", (e) => console.error(\"Failed\n\", e))" 
```

It tries to connect to the GH API and it should print `Works` finally. If not something with your Node installation may be wrong. Wrongly configured maybe?

**Comment by petermuessig** [comment]
Inactive issue, hence closing it.
