### ISSUE TITLE
Missing prompt for git repo initialization

### ISSUE THREAD

**Issue by dfenerski** [SAP/generator-easy-ui5#109]
In a monorepo context, generating a git sub-repo is not needed and worse, confuses git which files to track even after the deletion of the `.git` directory. AFAIK there is no prompt or option to disable this, or am I missing something? Thanks in advance!

**Comment by petermuessig** [comment]
@dfenerski - do I get it right, you want to use a generator within you mono-repo and you want to avoid calling `git init` right? which subgenerator did you use?

**Comment by dfenerski** [comment]
@petermuessig yes, this is exactly my goal. I am using `ts-app`

**Comment by petermuessig** [comment]
Ok, I'll check - this should be fixed here:
https://github.com/ui5-community/generator-ui5-ts-app/blob/main/generators/app/index.js#L172-L190

The `end()` step would also need a property to suppress the git initialization...

**Comment by dfenerski** [comment]
I can try to whip up a PR if that's acceptable? Would be like my first contribution ever :smiley:

**Comment by matseee** [comment]
It would be great if we could have this option in the [generator-ui5-project](https://github.com/ui5-community/generator-ui5-project) generator as well. I will create a pull request with the same changes as in the pull request https://github.com/ui5-community/generator-ui5-ts-app/pull/16.
