### ISSUE TITLE
npm update failure for generator-easy-ui5 dependency

### ISSUE THREAD

**Issue by ramsudharsan** [SAP/generator-easy-ui5#117]
## Easy-Ui5 version: 3.5.1

> Run `yo easy-ui5 --plugins` to print all relevant version strings

Node.js: v19.6.1
yeoman-environment: 3.15.1
generator-easy-ui5: 3.5.1
home: C:\Users\USERNAME\AppData\Roaming\npm\node_modules\generator-easy-ui5
pluginsHome: C:\Users\USERNAME\AppData\Roaming\npm\node_modules\generator-easy-ui5\plugin-generators

Available generators:
  - ui5-project: 0.3.1

## Steps to reproduce the problem:

1. Install yo and generator-easy-ui5 with the command: **npm install -g yo generator-easy-ui5**
2. Update global npm packages using the command: **npm update -g**

## What is the expected result?
The npm should update all the packages which are installed globally such as yo and generator-easy-ui5 (including its dependencies).

## What happens instead?
The following npm error is shown:
npm ERR! code ENOVERSIONS
npm ERR! No versions available for generator-template-ui5-project

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Local\npm-cache\_logs\2023-02-20T10_27_46_718Z-debug-0.log

## Any other information? (attach screenshot if possible)
Log File: [2023-02-20T10_27_46_718Z-debug-0.log](https://github.com/SAP/generator-easy-ui5/files/10783505/2023-02-20T10_27_46_718Z-debug-0.log)

![image](https://user-images.githubusercontent.com/6994262/220083804-5fce566c-4868-430e-b339-5ed4dd519cb8.png)

**Comment by petermuessig** [comment]
We will change the architecture of Easy UI5 soon to install the plugin generators in the user home rather than the global node modules folder. With that this issue will be solved. Keep you posted...
