### ISSUE TITLE
easy ui5 & ui5 tolling V3 

### ISSUE THREAD

**Issue by octavonu** [SAP/generator-easy-ui5#121]
Hello,

easy ui5 generator doesn't work with node 18 but ui5 tolling V3 requires node 18.

Is this repo/project obsolete or  not maintained anymore?

Thank you

**Comment by petermuessig** [comment]
Hi @octavonu, the repository is still maintained. @nicoschoenteich, we need to take a look.

**Comment by petermuessig** [comment]
Thanks for the hint. We are currently checking the `generator-easy-ui5` and the `generator-ui5-project` to update both to match the latest OSS versions and keep track with the UI5 tooling updates. Should be updated the next days...

**Comment by petermuessig** [comment]
Hi @octavonu,

together with @nicoschoenteich I merged the following PR today:
https://github.com/ui5-community/generator-ui5-project/pull/67

Now the project generator should also work with Node 18.

Cheers!
