### ISSUE TITLE
env.lookup(...).filter is not a function

### ISSUE THREAD

**Issue by signix** [SAP/generator-easy-ui5#132]
## Easy-Ui5 version:

> Run `yo easy-ui5 --plugins` to print all relevant version strings
yo easy-ui5 --plugins

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.6.3 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Node.js: v18.18.2
yeoman-environment: 3.19.3
generator-easy-ui5: 3.6.3
home: C:\Users\simon.georges\AppData\Roaming\npm\node_modules\generator-easy-ui5
pluginsHome: C:\Users\simon.georges\.npm\_generator-easy-ui5\plugin-generators

Available generators:
✖ An error occured while running easy-ui5:app#prompting
Error easy-ui5 --plugins

Cannot read properties of null (reading '1')

## OS/version:
Windows 11
## Steps to reproduce the problem:

1. Step 1
Install NodeJS (tested with version 20 and 18)
2. Step 2
npm install -g yo generator-easy-ui5
3. Step 3
execute yo easy-ui5 project

## What is the expected result?
project generation

## What happens instead?
✖ An error occured while running easy-ui5:app#prompting
Error easy-ui5 project

env.lookup(...).filter is not a function
## Any other information? (attach screenshot if possible)
I was trying to use the ts-app-fcl module but have the error even with only project.

![image](https://github.com/SAP/generator-easy-ui5/assets/6778092/88453786-35b8-47cb-b3b9-d4de39b1c189)

**Comment by cpa-gecko** [comment]
Looks like `lookup` is a promise now, works if you await the return like this:

`let subGenerators = (await env.lookup({ localOnly: true, packagePaths: generatorPath })).filter((sub) => {`

**Comment by cpa-gecko** [comment]
Looks like `lookup` is a promise now, works if you await the return like this within generator-easy-ui5 `index.js` line 640:

`let subGenerators = (await env.lookup({ localOnly: true, packagePaths: generatorPath })).filter((sub) => {`

**Comment by signix** [comment]
Make sense.
Do you want to do the fix or should I add a pull request ?
How can I test it ?
Thank you

**Comment by cpa-gecko** [comment]
you can modify the `index.js` in your node_modules folder. that got it working again for me

**Comment by fleischr** [comment]
will be glad to help test too! got the same issue

**Comment by vobu** [comment]
> Make sense. Do you want to do the fix or should I add a pull request ? How can I test it ? Thank you

bring in that PR - I‘ll try adding a unit test for it. Then I‘ll assign to @cpa-gecko and @fguldner for review!

**Comment by cpa-gecko** [comment]
created the PR: https://github.com/cpa-gecko/generator-easy-ui5/commit/c6b6050da63f665668a7e79376ba59992d5676ae

**Comment by sunbaby2** [comment]
Hello, even with the proposal fix, I still get the error. 
✖ An error occured while running easy-ui5:app#prompting
Error easy-ui5 project 

env.lookup(...).filter is not a function

**Comment by ABVN-Chuong** [comment]
![image](https://github.com/SAP/generator-easy-ui5/assets/140793877/25c2ef4a-c9a4-4903-880e-002abac329a7)
I got the same problems
How can I fix that ?
Thanks

**Comment by DominikZ2001** [comment]
Same here

**Comment by petermuessig** [comment]
https://www.npmjs.com/package/generator-easy-ui5

Version 3.7.0 is released and available!
