### ISSUE TITLE
[error] No parser could be inferred for file / Ignored unknown option --plugin-search-dir=..

### ISSUE THREAD

**Issue by loograt** [SAP/generator-easy-ui5#134]
## Easy-Ui5 version:

> Run `yo easy-ui5 --plugins` to print all relevant version strings

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.6.3 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Node.js: v18.18.2
yeoman-environment: 3.19.3
generator-easy-ui5: 3.6.3
home: /Users/gabrielsanroman/.npm-packages/lib/node_modules/generator-easy-ui5
pluginsHome: /Users/gabrielsanroman/.npm/_generator-easy-ui5/plugin-generators

Available generators:
  - ui5-project: 0.3.1

## Steps to reproduce the problem:

1. Step 1
Install NodeJS version 18
2. Step 2
npm install -g yo generator-easy-ui5
3. Step 3
execute yo easy-ui5 project

## What is the expected result?
project generation

## What happens instead?
> myUI5App@0.0.1 lint-fix
> eslint ./**/webapp/**/*.js --fix && prettier --plugin-search-dir=. --write ./**/webapp/**/*.{js,xml} --no-error-on-unmatched-pattern

[warn] Ignored unknown option --plugin-search-dir=..
uimodule/webapp/controller/App.controller.js 26ms
uimodule/webapp/controller/BaseController.js 10ms
uimodule/webapp/controller/MainView.controller.js 1ms
uimodule/webapp/model/formatter.js 1ms (unchanged)
uimodule/webapp/model/models.js 2ms
uimodule/webapp/test/testsuite.qunit.js 3ms (unchanged)
[error] No parser could be inferred for file "/Users/gabrielsanroman/SAP/com.myorg.myUI5App/uimodule/webapp/view/App.view.xml".
[error] No parser could be inferred for file "/Users/gabrielsanroman/SAP/com.myorg.myUI5App/uimodule/webapp/view/MainView.view.xml".
✖ An error occured while running ui5-project:app#end
Error easy-ui5 project 

Command failed with exit code 2: npm run lint-fix

## Any other information? (attach screenshot if possible)
It seems it picks up prettier version 3.1 instead of 2.8.8 and fails on a deprecated option

<img width="788" alt="Screenshot 2023-11-20 at 13 46 01" src="https://github.com/SAP/generator-easy-ui5/assets/30101325/87a8645b-71e4-4a93-b4be-9c75ff6901a1">
<img width="1548" alt="Screenshot 2023-11-20 at 13 47 22" src="https://github.com/SAP/generator-easy-ui5/assets/30101325/c52c1767-2218-4067-9c3d-379ae9ba276e">

**Comment by ashrafalimohamed188** [comment]
I am also facing same issue.

**Comment by rxunxk** [comment]
Any update? I am having the same issue :(
![image](https://github.com/SAP/generator-easy-ui5/assets/37786416/a78f04bc-3901-4c29-b4bf-dc4c984d5559)

**Comment by thavasisekar** [comment]
still facing the issue

**Comment by ashrafalimohamed188** [comment]
[rxunxk](https://github.com/rxunxk) and [loograt](https://github.com/loograt) try to refer this #138

**Comment by petermuessig** [comment]
Issue is tackled in #138
