### ISSUE TITLE
env.lookup(. . . . ).filter is not a function:

### ISSUE THREAD

**Issue by ashrafalimohamed188** [SAP/generator-easy-ui5#137]
Easy-Ui5 version: 3.6.3
Run yo easy-ui5 --plugins to print all relevant version strings

OS/version: windows 11/ 22H2
node version:v18.17.0
Browser/version (+device/version):

Steps to reproduce the problem:
Step 1
Install NodeJS version 18
Step 2
npm install -g yo generator-easy-ui5
Step 3
execute yo easy-ui5 project

What is the expected result?
project creation.

What happens instead?
An error occured while running easy-ui5:app#prompting
Error easy-ui5 project

env.lookup(. . . . ).filter is not a function.

Any other information? (attach screenshot if possible)

![Screenshot (178)](https://github.com/SAP/generator-easy-ui5/assets/146168668/c56313c9-1635-470c-80ec-bc06e3276bcc)

**Comment by vobu** [comment]
this just got resolved via #133

**Comment by akudev** [comment]
I can confirm the fix works. Thanks!

**Comment by ashrafalimohamed188** [comment]
Thanks
