### ISSUE TITLE
[error] No parser could be inferred for file

### ISSUE THREAD

**Issue by ashrafalimohamed188** [SAP/generator-easy-ui5#138]
hello,
Steps to reproduce the problem:
Step 1
Install NodeJS version 18
Step 2
npm install -g yo generator-easy-ui5
Step 3
execute yo easy-ui5 project

What is the expected result?
project generation

Issue explaination:
i was trying to create project with generator-easy-ui5,but i am facing  the following issue i have tried many node versions but still end up with same issue, kindly help me to overcome this issue.  

![Screenshot 2023-12-06 110317](https://github.com/SAP/generator-easy-ui5/assets/146168668/5b96375e-c03e-48d3-a2f1-135f725ebdfb)
 Thanks.

**Comment by bit-mschwingenschloegl** [comment]
Got the same problem. 
`yo easy-ui5 project` causes `[error] No parser could be inferred ...`
It seems that `yo easy-ui5 app` seems to work (See community project https://github.com/ui5-community/generator-ui5-app)
At the moment I am not sure about the differences between `project` and `app`

**Comment by ashrafalimohamed188** [comment]
[bit-mschwingenschloegl](https://github.com/bit-mschwingenschloegl)
Is it working?

**Comment by ashrafalimohamed188** [comment]
#[ziyang-works](https://github.com/ziyang-works)
Thanks a Lot.

**Comment by vobu** [comment]
excellent, guys! and @ziyang-works - what do you think about putting your solution into a Pull Request?! Would be cool to have it in the codebase 🙌

**Comment by vobu** [comment]
> Got the same problem. `yo easy-ui5 project` causes `[error] No parser could be inferred ...` It seems that `yo easy-ui5 app` seems to work (See community project https://github.com/ui5-community/generator-ui5-app) At the moment I am not sure about the differences between `project` and `app`

`yo easy-ui5 app` → will utilize the [sub-generator „generator-ui5-app“](https://github.com/ui5-community/generator-ui5-app) for bootstrapping a JS UI5 app
`yo easy-ui5 project` → uses the built-in (to easy-ui5) generator to bootstrap a full project

hth, v.
