### ISSUE TITLE
create new view

### ISSUE THREAD

**Issue by impnguyen** [SAP/generator-easy-ui5#14]
Easy-Ui5 version: 0.3.4

OS/version: Windows 10

Steps to reproduce the problem:
1. yo easy-ui5:newview
2. type in view name 'TileContainer'
3. return to commit creating depending controller

What is the expected result?
It should create a new view and depending controller

What happens instead?
error appears: "TypeError: Cannot read property 'toLowerCase' of undefined"

Any other information? (attach screenshot if possible)
![grafik](https://user-images.githubusercontent.com/2463861/67710326-08e87580-f9c0-11e9-85f5-3ab2cfa5bc95.png)

**Comment by IObert** [comment]
Hi @impnguyen,

I assume you did not create the project with easy-ui5. This is why the sub-generator cannot access these values.

I do understand that it makes sense to use sub-generators for existing projects too. I'll include this feature in the next release. Please let me know if it works

**Comment by impnguyen** [comment]
Hi, 
I created the whole project based on easy-ui5. I do not write a single line. 

Do you have an idea?

**Comment by IObert** [comment]
Mhhh, this is strange. Do you still encounter the same issue after updating to version 1.0.0?
`npm i -g generator-easy-ui5`

**Comment by impnguyen** [comment]
@IObert  thanks! I just updated to 1.0.0 and it works
