### ISSUE TITLE
Can't create Easy-UI5 project behind corporate proxy

### ISSUE THREAD

**Issue by LewkulitP** [SAP/generator-easy-ui5#142]
## Easy-Ui5 version:

(node:13636) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.8.0 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Node.js: v21.6.2
yeoman-environment: 3.19.3
generator-easy-ui5: 3.8.0
home: C:\Users\<user>\AppData\Roaming\npm\node_modules\generator-easy-ui5
pluginsHome: C:\Users\<user>\.npm\_generator-easy-ui5\plugin-generators

Available generators:
× An error occured while running easy-ui5:app#prompting
Error easy-ui5 --plugins

Cannot read properties of null (reading '1')

## OS/version:
Windows 10 Enterprise LTSC (Version 1809)

## Steps to reproduce the problem:

1. Step 1 run "yo easy-ui5 project"

## What is the expected result?
It should be possible to create a project in the following steps.

## What happens instead?
An error is displayed: 
"Failed to connect to GitHub to retrieve all available generators for "ui5-community" organization! Run with --verbose for details!"

## Any other information? (attach screenshot if possible)
"npm install" is working. 

"yo doctor" doesn't show any errors.:
![yeoman doctor](https://github.com/SAP/generator-easy-ui5/assets/100120832/4de73567-d549-4b2c-af85-0e6a937b207d)

It fails when trying to generate the easy-ui5 project:
![yeoman error](https://github.com/SAP/generator-easy-ui5/assets/100120832/4cec2f4f-a3be-461e-8ea9-9e5798464d91)
![yeoman error verbose without systemvariables](https://github.com/SAP/generator-easy-ui5/assets/100120832/2c0981ef-91db-41c6-af75-7670e964ed7b)

I've tried also setting Windows environment variables - they are then also shown in the verbose output:
![yeoman error verbose with systemvariables](https://github.com/SAP/generator-easy-ui5/assets/100120832/cc105f32-2c7b-47c9-a7da-51f3dbbe5dd0)

The proxy is set in .nprmc-file in the variables "PROXY", "HTTP_PROXY" and "HTTPS_PROXY":
![yeoman npmrc user](https://github.com/SAP/generator-easy-ui5/assets/100120832/e1307760-9f56-4726-bece-262f1282eeda)

**Comment by Kasde96** [comment]
We also have the problem that the easy-ui5 generator does not start and throws the following error.
Is there already a solution for this?

I get the error when I start the easy-ui5-generator in my WSL.
![image](https://github.com/SAP/generator-easy-ui5/assets/97966330/55e54cba-c46e-483f-a734-62df60d560ae)
I have already tried to update the easy-ui5-generator, but the error still occurs.

**Comment by Kasde96** [comment]
@petermuessig Do you know anything about this error? Are we doing something wrong?

**Comment by petermuessig** [comment]
Seems that the originally intended proxy support doesn't work - I need to verify this... Stay tuned...

**Comment by petermuessig** [comment]
I prepared a change now - seems that the behavior of the Node.js `fetch` API changed. It doesn't use the `GLOBAL_AGENT` configuration and therefore I switched to `node-fetch`. In addition, I extended to proxy configuration to be also injected from the npm config. So also you initial scenario will work once merged and released.
