### ISSUE TITLE
UI5 plugin generation failing

### ISSUE THREAD

**Issue by rlopmar** [SAP/generator-easy-ui5#146]
## Easy-Ui5 version: 

Node.js: v18.17.1
yeoman-environment: 3.19.3
generator-easy-ui5: 3.8.1

Available generators:
  - ui5-wdi5: 1.0.0
  - ui5-project: 0.3.1
  - ui5-flp-plugin: 0.0.1
  - ui5-app: 1.1.0

## OS/version:
Apple M2 Pro
iOS Version 14.5 

## Browser/version (+device/version):
NA - console execution

## Steps to reproduce the problem:

1. Step 1
Start easy-ui5 generator in console
> yo easy-ui5
2. Step 2
Select options in the command prompt as in the screenshot
3. Step 3
generator fails as show in the screenshot and code is not generated

![Screenshot 2024-08-20 at 08 21 33](https://github.com/user-attachments/assets/b2e2c885-4e6e-4fbe-86a8-d1a0e307861e)

## What is the expected result?
Code generated without failing

## What happens instead?
No code generated

## Any other information? (attach screenshot if possible)
Screenshot above

**Comment by petermuessig** [comment]
closed here in favor of the opened issue https://github.com/ui5-community/generator-ui5-flp-plugin/issues/5
