### ISSUE TITLE
SCP Portal Integration

### ISSUE THREAD

**Issue by andre68723** [SAP/generator-easy-ui5#16]
Hi,

it would be very helpful to also add a portal site to the generator for the generated UI5 app. This would allow to spin up a FLP with the generated app as tile in SCP easily.

Most of the topics are already taken care of in the `Cloud Foundry HTML5 Application Repository`, only some smaller parts would need to be added:
- Portal-Content + Portal as Ressources and their bindings
- Portal-Content Module Folder for the Site with package.json and site
- changes in approuter/xs-app.json, e.g. /cp.portal as welcomeFile 

References
- [Public Portal Documentation](https://help.sap.com/viewer/product/Portal_Service/1.0/en-US) 
- [Sample Repo](https://github.com/SAP-samples/cloud-portal-tutorial-samples)

Thanks, Andre

**Comment by IObert** [comment]
It took a while but now it should work now. I added it as a new target platform as you can see in this [tweet](https://twitter.com/IObert_/status/1237757108956913667).

Please let me know if it works as expected.
