### ISSUE TITLE
Instructions for usage in combination with CAP (after 'cds init')

### ISSUE THREAD

**Issue by piejanssens** [SAP/generator-easy-ui5#17]
From the working directory of my CAP app root I run `yo easyui5`.
After the wizard I end up with 'com.me.myui5app'.
Then I do `mv com.me.myui5app app`. As cds will serve what's in the `app` directory.
It works well and I can run the app after cds serves it with `https://localhost:4004/webapp`.

Is that the best practice? Or should I end up with index.html in the cds' `app` directory without `webapp`.

**Comment by IObert** [comment]
Good point! It makes sense to offer an option to create all files in the current directory.

I'll put it on my list and will change it when I got some time. Feel free to create a PR if this is urgent to you

**Comment by IObert** [comment]
The last version `1.0.3` will ask you if you want to create the project in the current working directory.

Please reopen the issue if needed
