### ISSUE TITLE
Please support CF with html5-repo and MULTIPLE ui5 apps

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP/generator-easy-ui5#19]
Easy-Ui5 version: 1.2.0

Steps to reproduce the problem:
1. Generate for CF wirh html5-repo

What is the expected result?
mta.yaml in main directory, fiori app with ui5.yaml in subdirectory, so additional fiori apps can be added in further subdirectories beneath main directory (this is the idea of the html5-repo usage anyway, ie to hve more than one fiori app)

What happens instead?
mta.yaml and ui5.yaml end up in same directory, second fiori app can't be added easily.

**Comment by IObert** [comment]
Hi,

this is a good suggestion. I was thinking about this recently! The problem that I see, is that I would make the folder structure incompatible between "standalone ui5 projects" and "CF-targetted projects". Having each web app in one subdirectory would look weird for the "standalone use case".

Do you have an idea on how to solve this problem? I don't want to say this is a reason not to do it, I was just wondering if there is a way.

Regards,
Marius

**Comment by DerGuteWolf** [comment]
Hi Marius,

I would make the difference in using html5-app-repo, as this is clearly intended for multiple html5-apps. For projects without html5-app-repo keep the current folder structure.

Perhaps you could change the wording from "Cloud Foundry HTML5 Application Repository" eg to "Cloud Foundry HTML5 Application Repository (multiple HTML5 apps, one MTA)" to makes thinks more clear.
Besides, one can still in shell/cmd change to the app subdir and eg execute ui5 serve for development purposes.

Also with your new new* commands it would be nice to have a newhtml5app then...

Regards,
  Wolfgang

**Comment by IObert** [comment]
A short update: I am working on an internal project where we have this situation as well. We already found a good way to handle this situation in the project and I'll try to incorporate this in the generator as soon as I have time for it :)

**Comment by IObert** [comment]
I just pushed a bunch of new commits to this repo. In the next version (2.0), you will be able to create additional web apps with `yo easy-ui5:newwebapp`. I won't publish the new version as I still need to do some testing but you can already test it locally if you are interested.

To test locally:
1. Remove current installation of easy-ui5
2. Clone this repo
3. Run `npm install` in this repo
4. Run `npm link` from the repo.

I'd be happy to hear your feedback.
