### ISSUE TITLE
generated view/controller names should not be prefixed with viewtype

### ISSUE THREAD

**Issue by fw2568** [SAP/generator-easy-ui5#2]
Easy-Ui5 version:
any

OS/version:
any 

Browser/version (+device/version):
any

Steps to reproduce the problem:
- generate a new project
or 
- add a new view

What is the expected result?
File names of views and controllers should follow the naming rules of other ui5 apps. For example https://github.com/SAP/openui5-sample-app/tree/master/webapp/view is created as **App**.view.xml

What happens instead?

The generated files are prefixed with the viewtype: **XMLApp**.view.xml

**Comment by IObert** [comment]
Good point! I'll fix this in the next version. Thanks :)
