### ISSUE TITLE
Change karma-ci.conf.js to allow running Karma-ci tests inside docker containers

### ISSUE THREAD

**Issue by geert-janklaps** [SAP/generator-easy-ui5#20]
Easy-Ui5 version: Latest

OS/version: Docker

Browser/version (+device/version): Chrome

Steps to reproduce the problem:
1. Create an empty template (I used the one for Cloud Foundry HTML5 repository)
2. Inside docker container run: npm run test

What is the expected result?
That the Karma tests succeed

What happens instead?
Karma / docker throws an error that the tests are not allowed to run without the --no-sandbox parameter

Any other information? (attach screenshot if possible)
This can be solved by adapting the file karma-ci.conf.js so it reflects (this change doesn't seem to impact running the tests locally in VS Code):
```
module.exports = function(config) {
	require("./karma.conf")(config);
	config.set({

		// test results reporter to use
		// possible values: 'dots', 'progress', 'coverage'
		// available reporters: https://npmjs.org/browse/keyword/karma-reporter
		reporters: ['progress'],

		// start these browsers
		// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
		browsers: ['ChromeHeadlessNoSandbox'],
                customLaunchers: {
                       ChromeHeadlessNoSandbox: {
                              base: 'ChromeHeadless',
                              flags: [
                                       '--no-sandbox', // required to run without privileges in docker
                                       '--user-data-dir=/tmp/chrome-test-profile',
                                       '--disable-web-security'
                             ]
                      }
                },

		// Continuous Integration mode
		// if true, Karma captures browsers, runs the tests and exits
		singleRun: true

	});
};
```

**Comment by IObert** [comment]
Thanks for your contribution! I modified the template file according to your suggestion
