### ISSUE TITLE
Create a new app from a git repository 

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/generator-easy-ui5#21]
sugestion

**Comment by IObert** [comment]
Hi @luizcarlospedrosogomes,

sounds interesting, can you please elaborate a bit more. E.g. how would this approach be different from a `git clone`? Would there be some additional calls to sub generators?

**Comment by luizcarlospedrosogomes** [comment]
using git clone, set repository for clone and branch

**Comment by luizcarlospedrosogomes** [comment]
https://github.com/SAP/generator-easy-ui5/pull/23 #23

**Comment by IObert** [comment]
To be honest, I'm still not sure what you mean. Can you add a short list with some bullet points that explain the sample flow?

**Comment by IObert** [comment]
Thanks for adding the PR. As far as I can see your extension would suppress the creating of the SAPUI5 resources, clone an existing repository, and add other modules (such as the approuter or the deployer) if needed.

Did I get that right? 

Wouldn't it be easier to make the sub-generators applicable to projects that were not created with easy-ui5 in the first place? I'm concerned that the extension you proposed, as far as I understand it, would remove the main purpose of this generator (which is generating SAPUI5 boilerplate code).

**Comment by luizcarlospedrosogomes** [comment]
The intention is very simple, to make the models more flexible.
The repository that must be nominated still needs to adopt the SAPUI5 layout standards.

do you have an example of how sub-generators could be used?

**Comment by IObert** [comment]
[Here](https://www.npmjs.com/package/generator-easy-ui5#sub-generators-to-avoid-recurring-tasks) is a list of the usage of sub generators. It could be possible to enable "yo easy-ui5:approuter" for standalone usage as well.

Do you also have an example of a repository that could be used? What would happen if the linked repository is empty, which effect would that have to the end result of the generator?

**Comment by luizcarlospedrosogomes** [comment]
#23 is only example. needs improvement
it is a fact that there are environments with different characteristics in relation to the available template.

I believe that with the clone of a repost compatible with yo generator, more business rules are possible.

**Comment by IObert** [comment]
I honestly still don't get the full idea. As far as I understand, this would introduce more confusion than it would help.
