### ISSUE TITLE
Adding a BaseController to the UI5 template

### ISSUE THREAD

**Issue by HeneryHawk** [SAP/generator-easy-ui5#22]
Easy-Ui5 version: 1.3.0

OS/version: any

Browser/version (+device/version): any

Steps to reproduce the problem:
1. Create a new UI5 project

What is the expected result?
The generator creates a project with included BaseController. All generated view controller extend this BaseController.

What happens instead?
No BaseController exists in a new generated project

Any other information? (attach screenshot if possible)
What do you think about adding a BaseController to the template for creating a UI5 app, with basic functionality.
If you like, I would do the work on that.

Best Regards
Simon

**Comment by IObert** [comment]
Hi @HeneryHawk,

that's a great idea! Please go ahead.

Regards,
Marius

**Comment by HeneryHawk** [comment]
Hi @IObert,
can you please take a look at the implementation? I'd make a pull request, if you think it's okay.

https://github.com/HeneryHawk/generator-easy-ui5

Regards Simon

**Comment by IObert** [comment]
Sorry for the late response. Yes, your code looks great.
Please make sure all the tests pass and open a PR.

Thanks for your contribution!

**Comment by IObert** [comment]
I just released another patch and your PR is officially in.
Thanks a lot!
