### ISSUE TITLE
Enhancement for gitignore

### ISSUE THREAD

**Issue by hschaefer123** [SAP/generator-easy-ui5#25]
Hi,
small enhancement request.

Maybe you can add `mta-*` to `.gitignore`

to make sure after downloaded mta log, they are not commited.

Logs are downloaded via
`cf dmol -i xxx-yyy-zzz`

and then stored/exploded in local dir 
`mta-xxx-yyy-zzz`

Regards
Holger

**Comment by IObert** [comment]
Good idea, I'll bring this in the next release!

Thanks!

**Comment by IObert** [comment]
Should be in the most recent version 1.3.2 :)
