### ISSUE TITLE
add template for custom tile

### ISSUE THREAD

**Issue by stesap** [SAP/generator-easy-ui5#27]
Easy-Ui5 version: 1.3.1

I like to contribute a template for generating custom tiles.

This [blog on SCN](https://blogs.sap.com/2020/03/23/custom-tiles-with-cloud-foundry-portal-cloud-platform/) described how to add custom tiles. In comparison to standard UI5 apps, the code structure is a little bit different and can be reduced a lot. For instance the router property in the manifest is not necessary.

What is the expected result?
- A new template command which generates a custom tile, similar to the UI5 app template.

I like to ask if this is a feature which is worth to add and if it fits to the roadmap of this tool?

**Comment by IObert** [comment]
Sure, sounds interesting.  Were you thinking of changing the default behavior of generator or did you want to add a prompt (e.g. "Use custom tile") and add this as an alternative code generation?

**Comment by stesap** [comment]
Great. My first idea a sub-generator, simliar to `yo easy-ui5:newview` command. But, when it's 'integrated' as an option when a Launchpad is created, it becomes more obvious to the user. What do you think?

**Comment by IObert** [comment]
I think so too. Please go ahead and open a PR whenever you are ready.
And thanks again for contributing

**Comment by stesap** [comment]
closed, due to lack of time
