### ISSUE TITLE
Exatraneous CF Destination middleware für Static websever

### ISSUE THREAD

**Issue by vickyokrm** [SAP/generator-easy-ui5#30]
**Easy-Ui5 version:** Latest

**Browser/version (+device/version):**

**Steps to reproduce the problem:**
1. Generate Scaffolding for openui5 webapp using yo easy-ui5
2. Select Static Webserver
3. Select OpenUI5 as CDN
4. Run

**What is the expected result?**
The UI5.yaml should not have middleware dependencies to CF(Specific: cf-destination)

**What happens instead?**
The ui5.yaml metadata uses a middleware configuration to cf-destionation, although it was not part of the package.json. This missing dependency prevents server from starting.

**ui5.yaml:** `    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        debug: true
        port: 1091
        xsappJson: approuter/xs-app.json
        destinations: []`

**.yo-rc.json:**
`{
  "generator-easy-ui5": {
    "projectname": "myApp",
    "namespace": "com.myorg",
    "platform": "Static webserver",
    "viewtype": "XML",
    "viewname": "Main",
    "ui5libs": "Content delivery network (OpenUI5)",
    "newdir": true
  }
}
`

**Comment by IObert** [comment]
Hi @vickyokrm,

thanks for opening the issue. The middleware that you are describing is actually part of all templates besides the one you choose :).
I thought that devs who need a CF destination, wouldn't select the `Static Webserver` target. This target was intended to be the most basic setup which doesn't make any assumptions on the environment.
Do you have a specific use case in mind, in which it might be useful to add the destination middleware but where CF is not the target platform of the app?

**Comment by nocin** [comment]
Hi @IObert,

also running into this error and was a bit confused, until I found this opened issue.
When I choose "static webserver" I also would expect being able to view the application directly in the browser after using "npm start" and not getting this middleware error. Now you always have to edit the ui5.yaml first to get the project running.

**Comment by IObert** [comment]
@vickyokrm  @nocin 

I'm sorry. I didn't understand the issue at first. Both of you are absolutely right, I'll fix this asap
