### ISSUE TITLE
"Application Router @ Cloud Foundry" fails to start locally

### ISSUE THREAD

**Issue by hosssa** [SAP/generator-easy-ui5#32]
**Easy-Ui5 version:** 
1.3.3

**OS/version:** 
Win 10

**Browser/version (+device/version):** 
n/a

**Steps to reproduce the problem:**
1. "yo easy-ui5"
```
{
  "generator-easy-ui5": {
    "projectname": "myApp",
    "namespace": "com.me",
    "platform": "Application Router @ Cloud Foundry",
    "viewtype": "XML",
    "viewname": "View",
    "ui5libs": "Content delivery network (SAPUI5)",
    "newdir": false,
    "namespaceURI": "com.me"
  }
}
```
2. "npm run start"
fails with error: 
xs-app.json/routes/0: Format validation failed (approuter\webapp is not a directory)

3. "npm run deploy"
works fine

**What is the expected result? What happens instead?**

When I change localDir in approuter/xs-app.json as follows: 
"localDir": "../webapp" 
"npm run start" runs successfully but "npm run deploy" fails while starting the deployed app.

**Possible solution**

"npm run start" works fine with an empty approuter/webapp folder. So maybe this could be created during the generation process.

The content of the approuter/webapp folder should not be in the git repo, so maybe this can be added to .gitignore by default.

**Comment by IObert** [comment]
Hi,

thanks for reporting this one. This is not an issue but the expected behavior as `npm (run) start` is the command that will be used when the approuter runs in the cloud. If you want to run it locally, please use `npm run local`

**Comment by hosssa** [comment]
Hi,

I have executed `npm run start` in the base dir (not in approuter). The command being executed is: `ui5 serve -o index.html` and this fails with the described error.

**Comment by IObert** [comment]
I understand this now. Yes, this is a problem. For now, I'd recommend removing the cfdestination middleware from the `ui5.yaml` page. 
I'll also open a PR to suggest a fix for the middleware.

**Comment by IObert** [comment]
I took this cfdestination middleware out for now and I'll put it back as soon as the fix is shipped

**Comment by IObert** [comment]
I brought it back in and updated the dependecy
