### ISSUE TITLE
Add standard neo app templates like Worklist, Master-Detail, list report and Fiori Elements

### ISSUE THREAD

**Issue by shinjans** [SAP/generator-easy-ui5#33]
Easy-Ui5 version: 2.1.0

What is the expected result?
Generate neo-app templates by running the generators like
**yo easy-ui5:worklist** to get the WebIDE templates. It will ask for server details (and other info similar to the templating wizard) and generate the worklist and object views.

I have plans to create all the neo-app generators including the Fiori Elements ones. Let me know if this is a direction you intend to explore or is this only for CF.

**Comment by IObert** [comment]
Thanks for opening this issue and making a contribution to this project.

The main idea of this project is to create a plain UI5 web app that can run on multiple web platforms. I'm afraid the templates you are suggesting, are not part of the scope of this project. Having said that, I absolutely understand that these are valid scenarios as well.

I think what you are looking for is offered by [this generator](https://www.npmjs.com/package/@sapui5/generator-sapui5-templates) here.
