### ISSUE TITLE
Support for generating Fiori Elements templates

### ISSUE THREAD

**Issue by geert-janklaps** [SAP/generator-easy-ui5#34]
When using easy-ui5 generator, currently it generates a blank SAPUI5 application. 
Personally I think it would be nice to have the templates available which for example are available in Web IDE:
![image](https://user-images.githubusercontent.com/2744548/82118102-3d155f00-9775-11ea-84a1-43fb71daa4e5.png)

I would definitely save some time when creating a new project based on Fiori Elements

**Comment by IObert** [comment]
Thanks for opening this issue and making a contribution to this project.

The main idea of this project is to create a plain UI5 web app that can run on multiple web platforms. I'm afraid the templates you are suggesting, are not part of the scope of this project. Having said that, I absolutely understand that these are valid scenarios as well.

I think what you are looking for is offered by [this generator](https://www.npmjs.com/package/@sapui5/generator-sapui5-templates) here.
