### ISSUE TITLE
Karma configuration for CI - Custom Launcher defined but not used

### ISSUE THREAD

**Issue by pfefferf** [SAP/generator-easy-ui5#36]
**Easy-Ui5 version**:
1.3.7

**OS/version:**
Windows -> but running generator on docker image (Ubuntu)

**Browser/version (+device/version):**
Latest Chrome

**Steps to reproduce the problem:**
1. Generate an OpenUI5 app with the generator
2. Run the app in a container
3. Execute tests with "npm run test" 

**What is the expected result?**
Successful execution of tests.

**What happens instead?**
Chrome cannot be started. Failed with error "ChromeHeadless stderr: Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted".

**Any other information? (attach screenshot if possible)**
The error appearing is a well known error when executing Chrome headless in a docker container. For that the "--no-sandbox" flag needs to be set. I guess you have considered that already in karam-ci.conf.js file (https://github.com/SAP/generator-easy-ui5/blob/master/generators/app/templates/karma-ci.conf.js) by defining a custom launcher ChromeHeadlessNoSandbox, but the "browsers" setting is set to "ChromeHeadless".
Should this set by default to "ChromeHeadlessNoSandbox" (as the solution here) or do you want to add some configurations to choose which launcher is executed (I don't think so). Here is the relevant code from the linked file:
`		browsers: ["ChromeHeadless"],
		customLaunchers: {
			ChromeHeadlessNoSandbox: {
				base: "ChromeHeadless",
				flags: [
					"--no-sandbox", // required to run without privileges in docker
					"--user-data-dir=/tmp/chrome-test-profile",
					"--disable-web-security"
				]
			}
		},`
I guess that the browsers array should be set to ChromeHeadlessNoSandbox by default.

**Comment by IObert** [comment]
Thanks for opening this issue. You are right, I wanted to reference the custom launcher. 
But somehow the test automation was still working without the configuration 🤔

Anyway, I fixed it (it will be part of the next major release)

**Comment by IObert** [comment]
It seems that this change broke my test suite now 😅 
I did some additional changes to the file to make sure my test suit passes again (also runs within a Docker image)
