### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by FOX-THE-KNIGHT** [SAP/generator-easy-ui5#39]
OS/version: windows 10 (Node.js - 10.14.2, npm - 6.4.2)

Steps to reproduce the problem:
1. run command npm i -g yo generator-easy-ui5
![trace](https://user-images.githubusercontent.com/30107832/93201465-e7b88100-f759-11ea-842e-fb1e7b41df05.PNG)

![error](https://user-images.githubusercontent.com/30107832/93201303-acb64d80-f759-11ea-89ef-70872cf2f5c6.PNG)

**Comment by IObert** [comment]
Can you try to run `npm i -g yo` first and then `npm i -g generator-easy-ui5`.
During which step do you see the error?

**Comment by FOX-THE-KNIGHT** [comment]
Got same error during run `npm i -g yo`
![image](https://user-images.githubusercontent.com/30107832/93206722-88ab3a00-f762-11ea-8ea4-9700bac6ab80.png)

**Comment by IObert** [comment]
I'll close this for now. Please reopen if you come across an issue in this generator.
