### ISSUE TITLE
Files in generated application shouldn't be executable

### ISSUE THREAD

**Issue by mjturner** [SAP/generator-easy-ui5#44]
**Easy-Ui5 version:**
2.2.1

**OS/version:**
macOS 10.15.7

**Browser/version (+device/version):**
N/A

**Steps to reproduce the problem:**
1. Use generator-easy-ui5 to scaffold a new UI5 application.
2. Files in `uimodule/webapp` that are not executable are marked as executable.

**What is the expected result?**
Non-executable files should not have the executable bit set.

**What happens instead?**
As above

**Any other information? (attach screenshot if possible)**
The following files in the repo are executable and do not need to be:

```
./generators/newwebapp/templates/uimodule/webapp/index.html
./generators/newwebapp/templates/uimodule/webapp/css/style.css
./generators/newwebapp/templates/uimodule/webapp/Component.js
./generators/newwebapp/templates/uimodule/webapp/model/models.js
./generators/newwebapp/templates/uimodule/webapp/manifest.json
./generators/newwebapp/templates/uimodule/webapp/i18n/i18n.properties
```

Happy to send a pull request to fix this.

**Comment by IObert** [comment]
Wow, I didn't notice that at all. Obviously, you are right. Thanks for opening the PR as well!

**Comment by mjturner** [comment]
No problem at all - thanks for merging it so quickly. Glad to make a very tiny contribution to a really useful project 👍
