### ISSUE TITLE
easy-ui5:uiveri5: Duplicate comma after baseUrl

### ISSUE THREAD

**Issue by georgbischoff** [SAP/generator-easy-ui5#47]
Easy-Ui5 version: v2.2.3

OS/version: Windows 10

Browser/version (+device/version): n/a

Steps to reproduce the problem:
1. Run yo easy-ui5:uiveri5
2. Choose authentication: SAP Fiori

What is the expected result?
A valid conf.js file is generated

What happens instead?
After the baseUrl, there are two "," instead of one ",":
**baseUrl: "http://localhost:8080",,**

Any other information? (attach screenshot if possible)
```
exports.config = {
  profile: "integration",
  baseUrl: "http://localhost:8080",,
  auth: {
    // provide credentials as params when running the test:
    // uiveri5 --params.user=<user> --params.pass=<pass>
    "fiori-form": {
      user: "${params.user}",
      pass: "${params.pass}"
    }
  }
};

```

**Comment by IObert** [comment]
I suppose this has been fixed the with commit above. Please reopen if the issue still persists.
