### ISSUE TITLE
easy-ui5:uiveri5: Typo in page object action

### ISSUE THREAD

**Issue by georgbischoff** [SAP/generator-easy-ui5#48]
Easy-Ui5 version: v2.2.3

OS/version: Windows 10

Browser/version (+device/version): n/a

Steps to reproduce the problem:
- Run yo easy-ui5:uiveri5
- Do you want to add a page object? Yes
- Page object name: home
- Add action with name (empty string to skip actions): iSelectBook

What is the expected result?
A valid action is generated.

What happens instead?
The action contains a small typo ("c" of controlType is missing):
**ontrolType: "sap.m.Button"**

Any other information? (attach screenshot if possible)
```
actions: {
      // add action functions here
      iSelectBook: function () {
        element(by.control({
          ontrolType: "sap.m.Button"
        })).click();
      }
    },
```

**Comment by IObert** [comment]
I suppose this has been fixed the with commit above. Please reopen if the issue still persists.
