### ISSUE TITLE
Application Router @ Cloud Foundry : new project is ending with error

### ISSUE THREAD

**Issue by mnkv1988** [SAP/generator-easy-ui5#57]
Easy-Ui5 version:
6.14.8

OS/version:
Windows

Browser/version (+device/version):
Chrome , BAS

Steps to reproduce the problem:
1) user: projects $ yo easy-ui5
2) How do you want to name this project? test
3) Which namespace do you want to use? com.sample
4) On which platform would you like to host the application? Application Router @ Cloud Foundry
5) Which view type do you want to use? XML
6) How do you want to name your main view? home
7) Where should your UI5 libs be served from? Content delivery network (SAPUI5)
8) Would you like to create a new directory for the project? Yes
9) npm start

What is the expected result?
start the url in localhost
What happens instead?
![image](https://user-images.githubusercontent.com/35804439/103858899-2abeab80-50df-11eb-8a5d-29cdbf64610d.png)

Any other information? (attach screenshot if possible)
Targetting as a cloud foundry application

**Comment by IObert** [comment]
Hi,

thanks for opening this issue. I have a few questions about the information you provided above. 

You said that you are using SAP Business Application Studio  (I guess that's what you mean with "BAS") but the screenshot shows a Windows terminal. Can you clarify this?

You stated that you use version 6.14.8 which does not exist. The latest version is 2.4.2. Can you run `npm -g ls generator-easy-ui5` to check which version you are using instead (and update if it's not the latest one)?

**Comment by vobu** [comment]
just by chance, also ran into this issue today.
there simply is no `uimodule/webapp/xs-app.json` created when using the "Application Router @ Cloud Foundry" project type creation.
quick workaround is to comment out the `ui5-middleware-cfdestination` custom server middleware in `uimodule/ui5.yaml`.

env:
- node v15.5.1
- generator-easy-ui5 v2.4.2
- macOS 11.1

**Comment by IObert** [comment]
Ah, now I see the problem. Thanks @vobu 

@mnkv1988 You can comment out that line or change it to `xsappJson: approuter/xs-app.json`. I'll fix the generator tomorrow.

**Comment by IObert** [comment]
Thanks for reporting. The issue should be fixed now
