### ISSUE TITLE
MTA deployment doesn't work due to zipped uimodule

### ISSUE THREAD

**Issue by jdtimmerman** [SAP/generator-easy-ui5#59]
**Easy-Ui5 version:**
```
$ npm -g ls generator-easy-ui5
/usr/lib
└── generator-easy-ui5@2.4.2 
```
**OS/version:**
```
$ uname -a
Linux X 5.4.85-1-MANJARO #1 SMP PREEMPT Mon Dec 21 21:38:53 UTC 2020 x86_64 GNU/Linux
```

**Browser/version (+device/version):**
Not applicable

**Steps to reproduce the problem:**
1. Generate a new project
2. Build an MTAR with `npx mbt build`
3. Deploy to cloudfoundry using `cf deploy mta_archives/MyApp_0.0.1.mtar`
4. Open the deployed app on https://XXX.hana.ondemand.com/ 

**What is the expected result?**
- Opening the URL immediately displays whatever app i've build

**What happens instead?**
- The browser shows 'Not found', with a 404 header
- Opening https://XXX.hana.ondemand.com/uimodule/uimodule.zip downloads a zip-file containing the contents of my app

**Any other information? (attach screenshot if possible)**
Running `npx mbt build` in my project's root dir results in the following files in my project:
```
approuter
`-- webapp
    |-- resources
    |   |-- sap
    |   |   |-- ...
    |   |-- jquery.sap.act-dbg.js
    |   |-- jquery.sap.act.js
    |   |-- etc...
    `-- uimodule.zip
```

In `uimodule/ui5.yaml` there is a small section with a ui5-task-zipper
```
builder:
  customTasks:
    - name: ui5-task-zipper
      afterTask: uglify
      configuration:
        archiveName: uimodule
```
when I disable this part, I no longer get a zip in my approuter deployment and the apps works as I would expect

**Comment by jdtimmerman** [comment]
While typing up this issue, someone else reported the same issue in https://github.com/SAP/generator-easy-ui5/issues/58. I'll close this one because @vobu submitted his issue first

**Comment by vobu** [comment]
😆 that one time where being the first is actually not what you want 🤣

**Comment by jdtimmerman** [comment]
I might have beaten you to it if I wouldn't have procrastinated by making a nice ascii representation of my file system ;)
