### ISSUE TITLE
test folder is generated directly to the project and not within the webapp folder

### ISSUE THREAD

**Issue by StefanButscher** [SAP/generator-easy-ui5#60]
Easy-Ui5 version: latest

OS/version: windows 10, sap image, latest

Browser/version (+device/version):  chromes 87.0.4280.141 

Steps to reproduce the problem:
1.  I open a project without tests in VS code and run yo easy-ui5:opa5
2.  The test folder is created on the project level

What is the expected result?
3. The Fiori pipeline requires a different folder setep
    https://github.wdf.sap.corp/pages/S4FIORI-CD/fiori-pipeline-docs/stages/karma/

The test folder should needs to be within the webapp folder.

What happens instead?

The test folder is directly on the project 

Any other information? (attach screenshot if possible)

You can use the project, remove the test folder and remove the test folder
 https://github.wdf.sap.corp/d050449/ASEUI5Training

**Comment by IObert** [comment]
Thanks for opening this issue, @tsaleksandrova can you please comment here?

**Comment by IObert** [comment]
I just merged the fix, the next version should be available in the next few days.
Thanks again for reporting the issue and thank you @tsaleksandrova for the fix :)
