### ISSUE TITLE
Include mockserver in apps generated for Netweaver

### ISSUE THREAD

**Issue by unkoder-dev** [SAP/generator-easy-ui5#65]
Using the generator for a Netweaver application does not produce the localService folder nor the "start-local" task in package.json. It would be great to have the possibility to add a service metadata.xml and service data in a .json file to be able to run the app locally without backend server.

Among other cases, this would help create examples people can download and run without having to create the backend service in an SAP System.

**Comment by IObert** [comment]
I agree that would be a great feature (and thanks for opening it)! 

I don't think I'll have time for this in the next few weeks but I'll mark the issue as "good first issue". Maybe someone wants to take it!

**Comment by IObert** [comment]
We moved the code that is addressed by this issue to another repo. Let's continue this discussion here: ui5-community/generator-ui5-project#4
