### ISSUE TITLE
Limit of alpha numeric project names for OPA5

### ISSUE THREAD

**Issue by StefanButscher** [SAP/generator-easy-ui5#68]
Dear colleagues,

when I run _yo easy-ui5:opa5_  for my project with name _sap.ui.demo.cart.controller_ I get the error message:

Please use alpha numeric characters only for the project name.

This restriction is difficult for FIORI development, projects follow the name pattern
**area.subarea.***

e.g. fin.ar.bankstatement.manage

Is it possible to soften this project name check ?

Thanks and Best Regards,
Stefan

**Comment by IObert** [comment]
We moved the code that is addressed by this issue to another repo. Let's continue this discussion here: ui5-community/generator-ui5-project#3
