### ISSUE TITLE
Error attempting to generate project

### ISSUE THREAD

**Issue by pedromagueija** [SAP/generator-easy-ui5#78]
## Easy-Ui5 version:
generator-easy-ui5@3.0.1

## OS/version:
Windows 10 (64bit)

## Browser/version (+device/version):
Microsoft Edge
Version 91.0.864.41 (Official build) (64-bit)

## Steps to reproduce the problem:

1. Install yo and easy-ui5 via NPM (npm install -g yo generator-easy-ui5)
2. Run project generator (yo easy-ui5 project)

## What is the expected result?

The project is generated successfully.

## What happens instead?

The following error occurs:

> Error easy-ui5 project
> 
> Cannot find module 'object-assign-deep'
> Require stack:
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\plugin-generators\generator-ui5-project\helpers\fileaccess.js
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\plugin-generators\generator-ui5-project\generators\additionalmodules\index.js
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\yeoman-environment\lib\util\esm.js
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\yeoman-environment\lib\store.js
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\yeoman-environment\lib\environment.js
> - ...\AppData\Roaming\npm\node_modules\generator-easy-ui5\generators\app\index.js
> - ...\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\util\esm.js
> - ...\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js
> - ...\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js
> - ...\AppData\Roaming\npm\node_modules\yo\lib\router.js
> - ...\AppData\Roaming\npm\node_modules\yo\lib\cli.js

## Any other information? (attach a screenshot if possible)

![ui5-error](https://user-images.githubusercontent.com/3015898/121502451-7a800680-c9e0-11eb-87cf-a6624d6989c6.png)

**Comment by IObert** [comment]
Thanks for opening the issue. Unfortunately, this is the wrong repo. I am aware of the issue now but you please create a new one here: <https://github.com/ui5-community/generator-ui5-project/issues>
This is the place where the project actually lives

**Comment by IObert** [comment]
Also, I just tested this on a Windows 10 VM and it worked perfectly there. Can you please provide some additional information if possible? Do you have a second machine you could try this on?

**Comment by pedromagueija** [comment]
@IObert Thanks for the reply. I've tried in another machine and indeed it works perfectly. So, I've removed both yo and easy-ui5 and reinstalled and that did the trick.

Probably should have tried it before reporting it. Sorry about that.

Thanks again, and thank you for your help.

**Comment by IObert** [comment]
No worries. I'm glad it works now ✌
