### ISSUE TITLE
yo easy-ui5 project  - Fails when behind corporate proxy

### ISSUE THREAD

**Issue by costa-satsati** [SAP/generator-easy-ui5#79]
When behind the corporate proxy the generator fails with the following error:
`Failed to connect to GitHub to retrieve available repository for "ui5-community" organization! Run with --verbose for details!
RequestError [HttpError]: request to https://api.github.com/orgs/ui5-community/repos failed, reason: connect ECONNREFUSED 52.63.231.178:443
    at C:\Users\sattsaevk\AppData\Roaming\npm\node_modules\generator-easy-ui5\node_modules\@octokit\request\dist-node\index.js:108:11
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports.prompting (C:\Users\sattsaevk\AppData\Roaming\npm\node_modules\generator-easy-ui5\generators\app\index.js:108:18) {      
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/orgs/ui5-community/repos',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'generator-easy-ui5:3.0.1 octokit-rest.js/18.6.7 octokit-core.js/3.5.1 Node.js/14.17.0 (win32; x64)'
    },
    request: { hook: [Function: bound bound register] }
  }
}`

The 'npm config proxy '   has been added but does not solve the issue. 

`// create the octokit client to retrieve the generators from GH org
    const octokit = new Octokit({
      userAgent: `${this.rootGeneratorName()}:${this.rootGeneratorVersion()}`,
      auth: this.options.ghAuthToken,
    });`

Needs to be passed on a proxy?

**Comment by vobu** [comment]
yep, your guess might be spot-on: https://github.com/octokit/octokit.js#constructor-options

**Comment by IObert** [comment]
Hi,

thanks for opening this issue. You are right, this is currently not supported but should be easily possible with arguments that are supplied to easy-ui5.

I just got back from vacation so I don't think I'll have time for this feature this or next week (maybe after). I'll also put this out as "good first issue" in case someone wants to take care of this.

**Comment by uxkjaer** [comment]
The issue is not Octokit, this works fine. However [yeoman ](https://github.com/yeoman/yo/issues/589#issuecomment-529630050)has a problem with the proxy. It doesn't use the http_proxy / https_proxy env variables.

You can try cmd 
`yo doctor`
and this should also fail
Set the GLOBAL_AGENT_HTTP_PROXY variable to your proxy and it should work.

**Comment by IObert** [comment]
Interesting! Thanks @uxkjaer

**Comment by softshipper** [comment]
I also have the same issue. The error messages come from the library `@octokit/rest`. I have created an application that illustrates the problem:

```
import { Octokit } from "@octokit/rest";
import { HttpProxyAgent } from "http-proxy-agent";
import { retry } from "@octokit/plugin-retry";

const ghOrg = "ui5-community",
    repoName = "generator-ui5-project",
    branch = "main";

const proxy = process.env.http_proxy;
const agent: HttpProxyAgent | unknown = proxy !== undefined ? new HttpProxyAgent(proxy) : null;

const RetryOctokit = Octokit.plugin(retry);
const octokit = new RetryOctokit({
    log: {
        debug: console.log,
        info: console.log,
        warn: console.log,
        error: console.log,
    },
    userAgent: "generator-easy-ui5",
    request: {
        agent: agent
    }
});

octokit.repos.getBranch({
    owner: ghOrg,
    repo: repoName,
    branch,
}).then(console.log)
    .catch(e => {
        console.error("#################### ERROR ####################");
        console.log(e);
    });
```
The question is, can the problem only be solved by the internal network people in my company or it is `generator-easy-ui5` problem.   

Thanks

**Comment by IObert** [comment]
This repo contains the actual logic used to scaffhold new UI5 projects. And as this is the common use-case to download easy-ui5, it happens automatically after easy-ui5 has been installed.

**Comment by softshipper** [comment]
@IObert What is your suggestion how to do it?

**Comment by IObert** [comment]
It's great that you were able to provide a minimal code sample to reproduce the issue. I have to say that I never saw such a problem and I still suspect this is cause by the configuration of your local network or GitHub. But not from EasyUI5 directly.


And as EasyUI5 is not an official tool by SAP (it's just an open source project that is maintained by SAP. If you are looking for a tool with a "guarantueed by SAP" label, you might be intersted in the SAP Fiori tools), I would ask you to find a fix (if possible) and document it here or even provide a pull request to avoid this in the future.

**Comment by petermuessig** [comment]
IMO, we should make the node proxy configuration available to the internally used `Octokit` APIs. I'll try to investigate this asap.
