### ISSUE TITLE
SAPUI5 Integration/Configuration (Question)

### ISSUE THREAD

**Issue by Jimmerz28** [SAP/generator-easy-ui5#8]
Easy-Ui5 version:
0.2.0

OS/version:
MacOS

Browser/version (+device/version):
-

Steps to reproduce the problem:
1. Use the scaffold to generate a project
2. Attempt to use a SAPUI5 specific component such as the FilterBar

What is the expected result?
That we can easily configure the scaffold to use a local "/resources" folder instead of the default OpenUI5.

What happens instead?
OpenUI5 is used.

Any other information? (attach screenshot if possible)
Are there any plans to be able to configure the scaffold to be able to integrate or use the SAPUI5 runtime? See https://tools.hana.ondemand.com/#sapui5

SAPUI5 doesn't seem to have its packages available at https://npm.sap.com/ which would have made it easier to integrate, but I assume that's due to some sort of licensing restriction(s)?

**Comment by IObert** [comment]
Great idea! I'll put it on my list

**Comment by IObert** [comment]
Hi @Jimmerz28,

I just had a deeper look into this and found a related issue SAP/ui5-tooling#130. This generator builds on top of the ui5 tooling project and therefore depends on that feature.
I'll keep this issue open and will check every now and then if there's new progress

**Comment by Jimmerz28** [comment]
Hey @IObert,

Thanks for the update, but that issue has already been closed so it doesn't seem like it'll be getting updated. Or do you mean you'll be able to provide internal updates if there's progression within SAP on the subject?

**Comment by IObert** [comment]
Easy-ui5 generated projects that use the ui5 tooling v2 and is capable of using local SAPUI5 resources now :)
