### ISSUE TITLE
[ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by developedbysom** [SAP/generator-easy-ui5#80]
Hello,

The npm module valid-filename raises issues while generating the easy-ui5 app.
The error described as below:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Somnath\AppData\Roaming\npm\node_modules\valid-filename\index.js
require() of ES modules is not supported.

Is this a known issue?
My current node version > 14.

Thanks.

**Comment by IObert** [comment]
A really strange problem. When I google this error message, it seems to be related to the used Node.js version.

Can you confirm that you use the most recent minor release of Node 14?

**Comment by petermuessig** [comment]
Any update on this issue, otherwise I would close it?

**Comment by developedbysom** [comment]
Yes..my bad in delaying to update, 

yeah after i took the latest node problem got resolved.

Many thanks.
