### ISSUE TITLE
Error Unexpected token '.' when running the easy-ui5 generator

### ISSUE THREAD

**Issue by AlexanderK22** [SAP/generator-easy-ui5#96]
## Easy-Ui5 version:
3.2.2

## OS/version:
Kubuntu 21.04

## Steps to reproduce the problem:

>Run `yo easy-ui5`

## What is the expected result?
Further prompts to create a project

## What happens instead?
Displays error `Unexpected token '.'`

## Any other information? (attach screenshot if possible)
![grafik](https://user-images.githubusercontent.com/60352903/153560466-9fc500ca-96cc-4a05-95cc-352b931dc595.png)

**Comment by nicogeburek** [comment]
Can you run `yo easy-ui5 --plugins` to check your version? (4.3.0 is your yo installation, not easy-ui5)

**Comment by AlexanderK22** [comment]
@petermuessig The node version is `v12.21.0`, npm is `8.5.0` and git is `2.30.2`.

Using an easy-ui5 version prior to 3.2 works just fine.

**Comment by petermuessig** [comment]
It's related to the usage of optional chaining in the generator which is not supported on Node v12:
https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12

Can you use a higher version of Node.js? V14? V12 goes OOM end of April 2022.

@nicogeburek we should upgrade the min requirement in the readme to use at least Node.js 14.

**Comment by nicogeburek** [comment]
https://github.com/SAP/generator-easy-ui5/pull/97

**Comment by AlexanderK22** [comment]
Updated Node.js to `v16.14.0` and the easy-ui5 generator works as expected.
